### ISSUE TITLE
$cordovaEmailComposer seemed to have stopped working with iOS9.2.1

### ISSUE THREAD

**Issue by lunchbag** [katzer/cordova-plugin-email-composer#160]
Can someone either confirm or deny that $cordovaEmailComposer doesn't seem to work anymore with iOS9.2.1? I have the following:

    $cordovaEmailComposer.open(email).then(null, function () {
       console.log('user cancelled email')
    });

and when it's invoked, it goes straight to logging 'user cancelled email'. This had been working (to my knowledge) up until the recent iOS update. I can confirm also that the email composer works on Android.

**Comment by lunchbag** [comment]
Upon further inspection, it seems that the issue is with isAvailable. I believe before, if Mail was not set up, it would invoke the set up page. Now it seems like it fails silently or gives false negatives.

**Comment by bayhall-digital** [comment]
This has been reported by a few threads - there is a fork uploaded onto npm which should solve the issue, but was unsuccessful for me. I found using the sharing plugin enabled the email and other options - but this will only suit if you want them to connect or send data through different channels.

**Comment by pbrisson** [comment]
Same issue here - I confirm I was able to get around it as @bayhall-digital said: I forked the plugin from here: https://www.npmjs.com/package/cordova-plugin-email-composer and it works properly on device (iPhone 5c running iOS 9.2) - although not on simulator (Mail opens then crashes, but I suspect it might be because it's not configured). Hope it helps someone until a fix is released!

**Comment by coderroggie** [comment]
+1 

Seeing same behavior, ios 9.2.1 not working whereas android is currently working fine.

**Comment by katzer** [comment]
@lunchbag I think yours is related to #166 - what I've fixed now

**Comment by lunchbag** [comment]
@katzer  I'm still seeing this issue. I'm on 0.8.3-dev.

On isAvailable, the app crashes:

2016-02-29 08:58:34.132 App[39561:2860052] -[NSNull hasSuffix:]: unrecognized selector sent to instance 0x106a3aaf0
2016-02-29 08:58:34.147 App[39561:2860052] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull hasSuffix:]: unrecognized selector sent to instance 0x106a3aaf0'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000106815e65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000106265deb objc_exception_throw + 48
	2   CoreFoundation                      0x000000010681e48d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x000000010676b90a ___forwarding___ + 970
	4   CoreFoundation                      0x000000010676b4b8 _CF_forwarding_prep_0 + 120
	5   App                            0x00000001044498fb -[APPEmailComposerImpl canSendMail:] + 107
	6   App                            0x0000000104448c1a __32-[APPEmailComposer isAvailable:]_block_invoke + 154
	7   libdispatch.dylib                   0x0000000108c90e5d _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x0000000108cb149b _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x0000000108c99bef _dispatch_root_queue_drain + 1829
	10  libdispatch.dylib                   0x0000000108c994c5 _dispatch_worker_thread3 + 111
	11  libsystem_pthread.dylib             0x0000000108fe9a9d _pthread_wqthread + 729
	12  libsystem_pthread.dylib             0x0000000108fe73dd start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by katzer** [comment]
@lunchbag,

I will look into it tomorrow, a null string seems to be the issue.

```
[NSNull hasSuffix:]: unrecognized selector sent to instance 0x106a3aaf0
```
