### ISSUE TITLE
Android -- Open Default App with Attachment, without Android Chooser

### ISSUE THREAD

**Issue by AbhishekJoshi** [katzer/cordova-plugin-email-composer#297]
I have a single mail app on my device, set as default Gmail. 

Are we able to send an email, with an attachment (pdf) to the default mail app, *without* having an app chooser/selector?

I currently only get one app in my chooser.

**Comment by cepm-nate** [comment]
Typically that's handled on the OS. There should be a 'Always use X' button when you pick an app.

**Comment by AbhishekJoshi** [comment]
Example off one of my burner phones.
This is running latest off Github, and only has a single email app and it is set as a default.

![image](https://user-images.githubusercontent.com/4527261/38006025-54f03f8a-3211-11e8-9205-032ccef06985.png)

**Comment by TheDuc** [comment]
I also have this same problem. Also, the 'mailto:' app behaves differently then a mailto link from within Chrome. When I use mailto also 'Whatsapp', 'save to drive' and 'bluetooth' appear for example, but they don't when using mailto in browser.

**Comment by TheDuc** [comment]
I see now that ACTION_SENDTO intent doesn't support sending attachments ([https://medium.com/@cketti/android-sending-email-using-intents-3da63662c58f](url))
In the same article is written to not use `Intent.createChooser()`. Without that the default mailapp will be opened.

**Comment by BKHines** [comment]
Is there any way to add an option to ignore chooser?  I changed my local plugin to implement the issue referenced above and I was able to select GMAIL as default and then it opened automatically every time.  The only code I had to change was to declare draft with final and then send draft into the startActivityResult like this:

`final Intent draft  = impl.getDraft(props);`
`...`
`cordova.getThreadPool().execute(new Runnable() {`
`            public void run() {`
`                cordova.startActivityForResult(plugin, draft, 0);`
`            }`
`        });`

Could you make an update to the plugin to toggle this line of code via another email composer option?

**Comment by katzer** [comment]
I've merged the PR!

**Comment by BKHines** [comment]
I"m not sure if I'm doing something wrong but I removed the plugin and then re-added it but I still get the old code.  Some way to force the CLI to get the latest code?

**Comment by katzer** [comment]
@BKHines I haven't released a new version yet. If you want to test the new code then you have to install the plugin with the git url - see the installation notes in the README.

**Comment by BKHines** [comment]
Ah, gotcha. Sorry about that, didn't even notice the same version number.
Thanks @katzer.

**Comment by BKHines** [comment]
With the latest version (0.9.1), I seem to be getting a chooser again, this time only with Samsung Email and gmail.  Browsing the code, it looks like it's still sending the draft into the activity instead of a chooser, but no matter what I do, it still opens the "Open With" dialog, both on a device or an emulator.  Was this change reverted with some other method?  Was there a newly added option I missed to ignore the chooser?  

If not, it could possibly be my device.  It's a new phone (S9+) so it's entirely possible even though the default email app is gmail, it may not be set up correctly.  I'm having another developer check it on their device as well to verify they're also seeing it.  It had previously worked for them and as far as I know, they're running the same device they were with the previous version where chooser was not showing.

**Comment by BKHines** [comment]
8.0.0. I'm wondering if it's something Samsung is forcing to try to make you use their email client. I've reached out to another developer who has a pixel 2 xl but I haven't heard back.
