### ISSUE TITLE
error: package android.support.v4.content does not exist

### ISSUE THREAD

**Issue by camdav** [katzer/cordova-plugin-email-composer#319]
Hi, I'm trying this plugin with a simple ionic blank starter template but running ionic cordova build android I have this errors:

/mails/platforms/android/app/src/main/java/de/appplant/cordova/emailcomposer/Provider.java:22: error: package android.support.v4.content does not exist
import android.support.v4.content.FileProvider;
                                 ^
/mails/platforms/android/app/src/main/java/de/appplant/cordova/emailcomposer/Provider.java:24: error: cannot find symbol
public class Provider extends FileProvider {
                              ^
  symbol: class FileProvider
/mails/platforms/android/app/src/main/java/de/appplant/cordova/emailcomposer/AssetUtil.java:276: error: cannot find symbol
            return Provider.getUriForFile(ctx, authority, file);
                           ^
  symbol:   method getUriForFile(Context,String,File)
  location: class Provider

How can i solve this?
Thanks

**Comment by ezraroda** [comment]
Submitted  PR #322

**Comment by katzer** [comment]
I've merged it and will publish it soon

**Comment by patrickian** [comment]
any news on this issue?

**Comment by ezraroda** [comment]
@katzer, npm version should be published to include the change.

@patrickian, you can use 
$ cordova plugin add https://github.com/katzer/cordova-plugin-email-composer.git

**Comment by katzer** [comment]
done

**Comment by Sampath-Lokuge** [comment]
@katzer I can still get this error. Please see more info here: https://github.com/ionic-team/ionic-native/issues/3611

**Comment by imperyal** [comment]
@katzer I was getting this error and changed "Provider.java". I replaced the import line:

```
/*import android.support.v4.content.FileProvider;*/
import androidx.core.content.FileProvider;
```

I only tested in the simulator but seems ok.
